# Generated by Django 3.2 on 2022-04-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='data')),
            ],
        ),
        migrations.CreateModel(
            name='health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='data')),
            ],
        ),
        migrations.CreateModel(
            name='technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='data')),
            ],
        ),
    ]
