# Generated by Django 4.0.3 on 2022-04-25 08:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_energy_health_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='myres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='energy',
            name='author',
        ),
        migrations.RemoveField(
            model_name='energy',
            name='date',
        ),
        migrations.AlterField(
            model_name='energy',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
