# Generated by Django 4.0.3 on 2022-04-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_myhelp_myrev_alter_health_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='author',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energy',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='energy',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
