# Generated by Django 4.0.3 on 2022-04-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_energy_author_energy_date_alter_energy_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='myregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='myres',
        ),
    ]
