# Generated by Django 4.0.3 on 2022-04-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_myregister_delete_myres'),
    ]

    operations = [
        migrations.CreateModel(
            name='userRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('Email', models.CharField(max_length=1000)),
                ('Password', models.CharField(max_length=1000)),
            ],
        ),
    ]
