# Generated by Django 3.2 on 2022-04-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='Address',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregister',
            name='DOB',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
