# Generated by Django 3.2 on 2022-04-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20220429_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='Address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='DOB',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
